'use strict';

export enum RoleType {
    USER = 'ROLE_USER',
    ADMIN = 'ROLE_ADMIN',
    ANONYMOUS = 'ROLE_ANONYMOUS',
    RECEPCION = 'ROLE_RECEPCION',
    LABORATORIO = 'ROLE_LABORATORIO',
    PRODUCCION = 'ROLE_PRODUCCION',
    CURADO = 'ROLE_CURADO',
    SALADERO = 'ROLE_SALADERO',
}
