export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  RECEPCION = 'ROLE_RECEPCION',
  LABORATORIO = 'ROLE_LABORATORIO',
  PRODUCCION = 'ROLE_PRODUCCION',
  CURADO = 'ROLE_CURADO',
  SALADERO = 'ROLE_SALADERO',
}
